# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BrazenBraden
email: braden@brazenbraden.com
description: > # this means to ignore newlines until "baseurl:"
  Developer, tinkerer and gamer. Family man, certified diver and rock climber.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://brazenbraden.com" # the base hostname & protocol for your site
twitter_username: brazenbraden
github_username:  brazenbraden
disqus_username:
timezone: Europe/London

staticman_url: https://bb-sm-blog-comments.onrender.com/v3/entry/github/brazenbraden/brazenbraden.github.io/master/comments

reCaptcha:
  siteKey: "agr4FYHHMio7PjuS7y78PKhEa7uSyp2T"
  secret: "frSpkKGzxlfTenzxzDQJEpFDKGW2wmHLrf0l7eYiim5pNqDPoQ9tp57ZkaN31FI7SPxHBnIdxnH/BUqHohz8bGP3M/rtFxPyFd/SoukHu5FLiXVfEGcu3oZz6I2OaluyQyYpTgdOOZqck7V2WCWr0xqNyy+DOIlu0rb/q3HHp6h0MRTbXLiG+K4qZZyfqUP2j4QF6BIx2FHe3NY4blKUQpOhl66CVpMOTkOKf7OJPYTGDqAHrerMBMGDFave3ZMhlZ7rj+PToZkIeWDNtgPQzZjNWoHqgZg/0m0QzPF14gTfi+/TG34k1LVpoOD2lTxE94/I/239rXzViyqU+H2ZOQ=="

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  style: compressed

images: '/assets/images'

defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
      lock_comments: false

