# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BrazenBraden
email: braden@brazenbraden.com
description: > # this means to ignore newlines until "baseurl:"
  Developer, tinkerer and gamer. Family man, certified diver and rock climber.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://brazenbraden.com" # the base hostname & protocol for your site
twitter_username: brazenbraden
github_username:  brazenbraden
disqus_username:
timezone: Europe/London

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  style: compressed

images: '/assets/images'
